---
- name: Setting up packages for wordpress(some extra just incase)
  hosts: localhost
  connection: local
  tasks:
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - curl
        - wget
        - git
        - vim
        - tree
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Add the user 'ansible' with a bash shell, Generate SSH key for user 'ansible'
      user:
        name: ansible
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa/pub
    - name: "Read a file content"
      shell: |
        cat ~/.ssh/id_rsa.pub
      register: file_content
    - name: setting config
      command: git config user.name 439774
    - name: setting config
      command: git config user.email therealkimbladi@gmail.com

